package com.sjg.mybatisGenerator.Model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
* Created by Mybatis Generator on 2019/07/05
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.holder_id
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private Integer holderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.reservation_id
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private Integer reservationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.license_plate
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private String licensePlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.model_id
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.free_time
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private String freeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.reservation_time
     *
     * @mbg.generated Fri Jul 05 11:29:17 CST 2019
     */
    private String reservationTime;
}