package com.sjg.zuzuCar.Model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
* Created by Mybatis Generator on 2019/07/05
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_name
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.net_name
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    private String netName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.permission
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    private String phone;
}