package com.sjg.zuzuCar.Mapper;

import com.sjg.zuzuCar.Model.Account;
import com.sjg.zuzuCar.Model.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

/**
* Created by Mybatis Generator on 2019/07/05
*/
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    @Delete({
        "delete from account",
        "where account_id = #{accountId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    @Insert({
        "insert into account (account_id, user_name, ",
        "net_name, password, ",
        "permission, phone)",
        "values (#{accountId,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{netName,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{permission,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR})"
    })
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    @Select({
        "select",
        "account_id, user_name, net_name, password, permission, phone",
        "from account",
        "where account_id = #{accountId,jdbcType=INTEGER}"
    })
    @ResultMap("com.sjg.zuzuCar.Mapper.AccountMapper.BaseResultMap")
    Account selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Fri Jul 05 11:32:50 CST 2019
     */
    @Update({
        "update account",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "net_name = #{netName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "permission = #{permission,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR}",
        "where account_id = #{accountId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Account record);
}