package com.sjg.zuzuCar.Mapper;

import com.sjg.zuzuCar.Model.Models;
import com.sjg.zuzuCar.Model.ModelsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

/**
* Created by Mybatis Generator on 2019/07/06
*/
public interface ModelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    long countByExample(ModelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int deleteByExample(ModelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Delete({
        "delete from models",
        "where model_id = #{modelId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Insert({
        "insert into models (model_id, model_name)",
        "values (#{modelId,jdbcType=INTEGER}, #{modelName,jdbcType=VARCHAR})"
    })
    int insert(Models record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int insertSelective(Models record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    List<Models> selectByExample(ModelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Select({
        "select",
        "model_id, model_name",
        "from models",
        "where model_id = #{modelId,jdbcType=INTEGER}"
    })
    @ResultMap("com.sjg.zuzuCar.Mapper.ModelsMapper.BaseResultMap")
    Models selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Models record, @Param("example") ModelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int updateByExample(@Param("record") Models record, @Param("example") ModelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int updateByPrimaryKeySelective(Models record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table models
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Update({
        "update models",
        "set model_name = #{modelName,jdbcType=VARCHAR}",
        "where model_id = #{modelId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Models record);
}