package com.sjg.zuzuCar.Mapper;

import com.sjg.zuzuCar.Model.ReservationForm;
import com.sjg.zuzuCar.Model.ReservationFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

/**
* Created by Mybatis Generator on 2019/07/06
*/
public interface ReservationFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    long countByExample(ReservationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int deleteByExample(ReservationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Delete({
        "delete from reservation_form",
        "where reservation_form_id = #{reservationFormId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer reservationFormId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Insert({
        "insert into reservation_form (reservation_form_id, holder_id, ",
        "reservation_id, license_plate, ",
        "model_id, free_start_time, ",
        "free_end_time, reservation_time)",
        "values (#{reservationFormId,jdbcType=INTEGER}, #{holderId,jdbcType=INTEGER}, ",
        "#{reservationId,jdbcType=INTEGER}, #{licensePlate,jdbcType=VARCHAR}, ",
        "#{modelId,jdbcType=INTEGER}, #{freeStartTime,jdbcType=BIGINT}, ",
        "#{freeEndTime,jdbcType=BIGINT}, #{reservationTime,jdbcType=BIGINT})"
    })
    int insert(ReservationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int insertSelective(ReservationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    List<ReservationForm> selectByExample(ReservationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Select({
        "select",
        "reservation_form_id, holder_id, reservation_id, license_plate, model_id, free_start_time, ",
        "free_end_time, reservation_time",
        "from reservation_form",
        "where reservation_form_id = #{reservationFormId,jdbcType=INTEGER}"
    })
    @ResultMap("com.sjg.zuzuCar.Mapper.ReservationFormMapper.BaseResultMap")
    ReservationForm selectByPrimaryKey(Integer reservationFormId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReservationForm record, @Param("example") ReservationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int updateByExample(@Param("record") ReservationForm record, @Param("example") ReservationFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    int updateByPrimaryKeySelective(ReservationForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_form
     *
     * @mbg.generated Sat Jul 06 01:22:22 CST 2019
     */
    @Update({
        "update reservation_form",
        "set holder_id = #{holderId,jdbcType=INTEGER},",
          "reservation_id = #{reservationId,jdbcType=INTEGER},",
          "license_plate = #{licensePlate,jdbcType=VARCHAR},",
          "model_id = #{modelId,jdbcType=INTEGER},",
          "free_start_time = #{freeStartTime,jdbcType=BIGINT},",
          "free_end_time = #{freeEndTime,jdbcType=BIGINT},",
          "reservation_time = #{reservationTime,jdbcType=BIGINT}",
        "where reservation_form_id = #{reservationFormId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ReservationForm record);
}